apiVersion: v1
kind: Service
metadata:
  name: f5-hello-world
  namespace: default
  labels:
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: ingress_pool
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: f5-hello-world