apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-service
spec:
  selector:
    matchLabels:
      run: web-service
  replicas: 3
  template:
    metadata:
      labels:
        run: web-service
    spec:
      containers:
        - name: nginx
          image: nginx