kind: ConfigMap
apiVersion: v1
metadata:
  name: web-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "nginx-plus",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
       "Common": {
          "class": "Tenant",
          "Shared": {
            "class": "Application",
            "template": "shared",
            "XFF_HTTP_Profile": {
              "class": "HTTP_Profile",
                "xForwardedFor": true
               }
       }
       },
        "AS3": {
          "class": "Tenant",
          "MyApps": {
             "class": "Application",
             "template": "generic",
             "ingress": {
                "class": "Service_HTTP",
                "virtualAddresses": ["10.1.10.101"],

               "virtualPort": 80,
               "remark":"ingress: f5demo.waf.http.v1",
               "pool": "ingress_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
               "policyWAF": {
                   "use": "My_ASM_Policy"
               }
#               "policyWAF":{"/Common/WAF_DevOps"},
               "securityLogProfiles": [
               {
                 "bigip": "/Common/Log all requests"
               }
               ]
             },
             "ingress_pool": {
                "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
             },
             
             "My_ASM_Policy": {
                "class": "WAF_Policy",
                "url": "https://github.com/darguello13/Revolution-F5-CIS/blob/master/WAF_Policy/Common_WAF_DevOps__2019-7-5_7-8-42__bigip1.agility-labs.io.xml",
                "ignoreChanges": false
                "enforcementMode": "transparent"
             }
             
             
       }
       }
    }
    }