kind: ConfigMap
apiVersion: v1
metadata:
  name: web-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
   {
      "class": "ADC",
      "schemaVersion": "3.2.0",
      "id": "5489432",
      "label": "ASM_policy_external_URL",
      "remark": "ASM_policy_external_URL",
      "Sample_app_sec_trans": {
         "class": "Tenant",
         "HTTP_Service": {
         "class": "Application",
         "template": "http",
         "serviceMain": {
            "class": "Service_HTTP",
            "virtualAddresses": [
              "10.1.10.101"
             ],
          "snat": "auto",
          "pool": "ingress_pool",
          "policyWAF": {
          "use": "My_ASM_Policy"
           }
           },
     
       "ingress_pool": {
          "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
                },

       "My_ASM_Policy": {
         "class": "WAF_Policy",
         "url": "https://github.com/darguello13/Revolution-F5-CIS/blob/master/WAF_Policy/Common_WAF_DevOps__2019-7-5_7-8-42__bigip1.agility-labs.io.xml",
         "ignoreChanges": false
         "enforcementMode": "transparent"
       }
     }
     }
    }