apiVersion: v1
kind: Pod
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  containers:
  - name: web-api
    image: diegoarg/acme-api-demo
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    imagePullPolicy: Always
    ports:
    - containerPort: 27017