apiVersion: v1
kind: Pod
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  containers:
  - name: web-api
    image: diegoarg/acme-api-demo
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    imagePullPolicy: Always
    ports:
    - containerPort: 27017
    
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: default
  labels:
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: acme_api_pool
spec:
  selector:
    app: web-api
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort