apiVersion: v1
kind: Pod
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  containers:
  - name: web-api
    image: diegoarg/acme-api-demo:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3000