kind: ConfigMap
apiVersion: v1
metadata:
  name: api-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.2.0",
        "id": "nginx-plus",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "Backend_Tenant": {
          "class": "Tenant"
       }
    }
    }